spring:
  application:
    name: SCore Authentication Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sgcore
          jwk-set-uri: http://keycloak:8080/realms/sgcore/protocol/openid-connect/certs
server:
  port: 8082
keycloak:
  token-uri: http://keycloak:8080/realms/sgcore/protocol/openid-connect/token