services:
  sgcore-cloud:
    image: sgcore-cloud
    container_name: sgcore-cloud
    build:
      context: ./sgcore-cloud
      dockerfile: Dockerfile
    ports:
      - "${SGCORE_CLOUD_HTTP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME:  ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${JWT_ISSUER_URI}
    depends_on:
      - postgres
      - keycloak
    networks:
      - sgcore-network

  sgcore-auth:
    image: sgcore-auth
    container_name: sgcore-auth
    build:
      context: ./sgcore-auth
      dockerfile: Dockerfile
    ports:
      - "${SGCORE_AUTH_HTTP_PORT}:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      KEYCLOAK_TOKEN_URI: ${KEYCLOAK_TOKEN_URI}
    networks:
      - sgcore-network

  sgcore-ui:
    image: sgcore-ui
    container_name: sgcore-ui
    build:
      context: ./sgcore-ui
      dockerfile: Dockerfile
    ports:
      - "${SGCORE_UI_HTTP_PORT}:80"
    depends_on:
      - sgcore-cloud
    networks:
      - sgcore-network

  postgres:
    container_name: sgcore-db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${SGCORE_POSTGRES_TCP_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sgcore-network

  keycloak:
    container_name: sgcore-keycloak
    image: quay.io/keycloak/keycloak:26.4.7
    command:
      - start-dev
      - --import-realm
    ports:
      - "${SGCORE_KEYCLOAK_HTTP_PORT}:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - sgcore-network

volumes:
  postgres-data:

networks:
  sgcore-network:
    name: sgcore-network
    driver: bridge